### ISSUE TITLE
[버그] 위치 정보가 업데이트 되지 않고 1분마다 업데이트

### ISSUE THREAD

**Issue by yonghanJu** [boostcampwm-2022/android05-MoGakRun#39]
## 🥸 버그 내용
- 1초마다 현재 위치를 확인해야 하는데 위치 정보가 업데이트 되지 않고 1분마다 업데이트됩니다.

## 🥲 버그 화면
- 버그가 발생하는 화면을 보여주세요.

## 🧐 의견
- 상황에 따라 잘 되기도 하고 안되기도 하는데 예상 이유를 작성했습니다
   - 외부 달리기 앱이랑 같이 켰을 때 더 잘 측정이 되는 현상이 있어서 해당 앱이 위치를 업데이트해준다고 생각됩니다.
   - `requestLocationUpdates()` 함수를 호출하지 않고 `lastLocation` 만 호출해서 위치가 업데이트 안됐다고 추측하고 있습니다.

## 🐛 버그 발생 위치
- 버그가 발생한 이슈 혹은 PR #38

**Comment by bngsh** [comment]
#38 러닝 화면 구현
