### ISSUE TITLE
#38 feat/running_tab 앱 빌드가 안됨

### ISSUE THREAD

**Issue by yonghanJu** [boostcampwm-2022/android05-MoGakRun#40]
## 🥸 버그 내용
- #38 앱 빌드가 안됨

## 🥲 버그 화면
```Error: Every Initializer needs to be accompanied by a corresponding <meta-data> entry in the AndroidManifest.xml file. [EnsureInitializerMetadata from androidx.startup]```                       

## 🧐 의견
- Meta Data가 빠져있는 것 같음

## 🐛 버그 발생 위치
- #38 

## 해결 여부
- [x] 해결

**Comment by soopeach** [comment]
요거 해결 원인이랑 과정들 정리해주시면 좋을 것 같아요!
